// cli_transport_usart6.c — USART6 / RS232 transport for TimbreOS CLI
//
// USART6 connects to the RS232 port on the extender board and is the
// default CLI transport — active from boot, no connection handshake needed.
//
// Input routing:
//   Before each keyIn() call, EmitEvent is pointed at usart6_emit so that
//   output is automatically directed back to RS232.
//   autoEchoOn() is used — the RS232 terminal expects the device to echo.
//
// TX is polled inside usart6_emit (called as an EmitEvent action).  At
// 115200 baud each byte takes ~87 µs; typical CLI output is short enough
// that spinning on TXE is acceptable in the cooperative scheduler.
//
// RX uses the RXNE interrupt.  The single-instance state machine
// (IDLE → QUEUED → RUNNING → REQUEUE) prevents queue overflow if bytes
// arrive faster than the action runs.
//
// Required wiring in stm32f4xx_it.c:
//   void USART6_IRQHandler(void) { usart6_rx_irq(); }

#include <stdint.h>
#include <stdbool.h>

#include "stm32f4xx_ll_usart.h"

#include "tea.h"
#include "cli.h"
#include "byteq.h"
#include "printers.h"

#include "cli_transport_usart6.h"

// ── Forward declaration ───────────────────────────────────────────────────────

static void usart6_rx_action(void);

// ── EmitEvent target — drains emitq to USART6 TX (polled) ───────────────────

static void usart6_emit(void) {
    while (qbq(emitq)) {
        uint8_t ch = pullbq(emitq);
        while (!LL_USART_IsActiveFlag_TXE(USART6)) { }
        LL_USART_TransmitData8(USART6, ch);
    }
    // Wait for the last byte to shift out before returning.
    while (!LL_USART_IsActiveFlag_TC(USART6)) { }
}

// ── Single-instance RX action state machine ───────────────────────────────────

// typedef enum {
//     USART6_IDLE,
//     USART6_QUEUED,
//     USART6_RUNNING,
//     USART6_REQUEUE,
// } usart6_state_t;

// static volatile usart6_state_t rx_state = USART6_IDLE;

// ── usart6_rx_irq — call from USART6_IRQHandler ───────────────────────────────
static BQUEUE(100, cliq);

void usart6_rx_irq(void) {
    pushbq(LL_USART_ReceiveData8(USART6), cliq);
    if (qbq(cliq) == 1)
        later(usart6_rx_action);

    // switch (rx_state) {
    //     case USART6_IDLE:
    //         rx_state = USART6_QUEUED;
    //         later(usart6_rx_action);
    //         break;
    //     case USART6_RUNNING:
    //         rx_state = USART6_REQUEUE;
    //         break;
    //     case USART6_QUEUED:
    //     case USART6_REQUEUE:
    //         break;
    // }
}

// ── usart6_rx_action — tea.c action, single-instance ─────────────────────────

static void usart6_rx_action(void) {
    // rx_state = USART6_RUNNING;

    // Direct output back to RS232 before processing any characters.
    when(EmitEvent, usart6_emit);
//    autoEchoOn();       // RS232 terminal expects device-side echo

    while (qbq(cliq))  keyIn(pullbq(cliq));
    // safe( if (qbq(cliq))  later(usart6_rx_action); )
    // switch (rx_state) {
    //     case USART6_REQUEUE:
    //         // Interrupt fired while we were running — more bytes may have arrived.
    //         rx_state = USART6_QUEUED;
    //         later(usart6_rx_action);
    //         break;
    //     case USART6_RUNNING:
    //         rx_state = USART6_IDLE;
    //         break;
    //     default:
    //         break;
    // }
}

// ── usart6_transport_init — call once from board init ────────────────────────


void usart6_transport_init(void) {
    // Enable USART6 RXNE interrupt — USART6 peripheral itself is already
    // initialised by MX_USART6_UART_Init() generated by CubeMX.
    LL_USART_EnableIT_RXNE(USART6);

    // Establish USART6 as the default CLI transport from boot.
    when(EmitEvent, usart6_emit);
    autoEchoOn();

    dotPrompt();
}
