#ifndef HTTP_CONTENT_H
#define HTTP_CONTENT_H

#include <stdint.h>
#include "byteq.h"
#include "cli.h"

// ── Flash-resident HTTP response ──────────────────────────────────────────────
// Each entry is a complete HTTP response: status line + headers + blank + body.
// Generated by the build pipeline (minify → convert → this file).
// Stored in flash — tcp_write() references these directly without copying.

typedef struct {
    const char *data;
    uint32_t    length;
} http_response_t;

typedef const http_response_t *(*http_handler_fn)(const char *req, uint16_t len);

// ── Route table entry ─────────────────────────────────────────────────────────
typedef struct {
    const char            *method;    /* "GET" or "POST"   */
    const char            *url;
    const http_response_t *response;  /* non-NULL: static  */
    http_handler_fn        handler;   /* non-NULL: dynamic */
} http_route_t;

// 
static const char s_404[] = "HTTP/1.0 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n";
static const char s_204[] = "HTTP/1.0 204 No Content\r\nContent-Length: 0\r\nConnection: close\r\n\r\n";
static const http_response_t http_404 = { s_404, sizeof(s_404)-1 };
static const http_response_t http_204 = { s_204, sizeof(s_204)-1 };

static const char index_html_data[] =
    "HTTP/1.0 200 OK\r\n"
    "Content-Type: text/html\r\n"
    "Connection: close\r\n"
    "\r\n"
    "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>STM32</title>"
    "<style>"
    "body{font-family:monospace;background:#111;color:#ccc;margin:0;padding:0}"
    ".tabs{display:flex;background:#222}"
    ".tab{padding:8px 18px;background:#333;color:#999;border:none;cursor:pointer;font-size:14px}"
    ".tab.on{background:#111;color:#0f0}"
    ".page{display:none;padding:10px}"
    ".page.on{display:block}"
    "table{border-collapse:collapse;width:100%}"
    "td{border:1px solid #444;padding:5px 8px}"
    "#out{background:#000;color:#0f0;height:380px;padding:8px;"
         "overflow-y:auto;white-space:pre-wrap;word-break:break-all;"
         "font-size:13px;border:1px solid #333}"
    "#irow{display:flex;margin-top:6px;gap:4px}"
    "#inp{flex:1;background:#000;color:#0f0;border:1px solid #444;"
         "padding:4px 6px;font-family:monospace;font-size:13px}"
    "#btn{background:#333;color:#0f0;border:1px solid #444;padding:4px 12px;cursor:pointer}"
    "</style></head><body>"
    "<div class=\"tabs\">"
    "<button class=\"tab on\" onclick=\"sw('st',this)\">Active Robot</button>"
    "<button class=\"tab\" onclick=\"sw('tm',this)\">Terminal</button>"
    "</div>"
    "<div id=\"st\" class=\"page on\">"
    "<table><tbody id=\"sb\"></tbody></table>"
    "</div>"
    "<div id=\"tm\" class=\"page\">"
    "<div id=\"out\"></div>"
    "<div id=\"irow\">"
    "<input id=\"inp\" type=\"text\" autocomplete=\"off\" autocorrect=\"off\""
    " autocapitalize=\"none\" spellcheck=\"false\" placeholder=\"command...\">"
    "<button id=\"btn\" onclick=\"send()\">Send</button>"
    "</div></div>"
    "<script>"
    "function sw(id,el){"
    "document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));"
    "document.querySelectorAll('.tab').forEach(t=>t.classList.remove('on'));"
    "document.getElementById(id).classList.add('on');el.classList.add('on');}"

    /* status polling */
    "setInterval(()=>{"
    "fetch('/status.json').then(r=>r.json()).then(d=>{"
    "document.getElementById('sb').innerHTML="
    "Object.entries(d).map(([k,v])=>"
    "'<tr><td>'+k+'</td><td>'+v+'</td></tr>').join('');"
    "}).catch(()=>{});},1000);"

    /* terminal SSE stream — push output from /term_stream */
    "(function(){"
    "const o=document.getElementById('out');"
    "const es=new EventSource('/term_stream');"
    "es.onmessage=function(e){o.textContent+=e.data;o.scrollTop=o.scrollHeight;};"
    "es.onerror=function(){};"
    "})();"

    /* command history (up/down arrows) + send (Enter or button) */
    "var hist=[],histIdx=0;"
    "function send(){"
    "const el=document.getElementById('inp');"
    "const txt=el.value;el.value='';"
    "if(txt){hist.push(txt);histIdx=hist.length;}"
    "const enc=new TextEncoder().encode(txt);"
    "const buf=new Uint8Array(enc.length+1);"
    "buf.set(enc);buf[enc.length]=0xD;"
    "fetch('/term_in',{method:'POST',body:buf}).catch(()=>{});}"

    "document.getElementById('inp')"
    ".addEventListener('keydown',e=>{"
    "if(e.key==='Enter'){send();}"
    "else if(e.key==='ArrowUp'){e.preventDefault();"
    "if(histIdx>0){histIdx--;e.target.value=hist[histIdx];}}"
    "else if(e.key==='ArrowDown'){e.preventDefault();"
    "if(histIdx<hist.length-1){histIdx++;e.target.value=hist[histIdx];}"
    "else{histIdx=hist.length;e.target.value='';}}});"
    "</script></body></html>";

static const http_response_t resp_index = {
    index_html_data,
    sizeof(index_html_data) - 1   /* exclude null terminator */
};

#endif // HTTP_CONTENT_H
