#ifndef HTTP_CONTENT_H
#define HTTP_CONTENT_H

#include <stdint.h>
#include "byteq.h"
#include "cli.h"

// ── Flash-resident HTTP response ──────────────────────────────────────────────
// Each entry is a complete HTTP response: status line + headers + blank + body.
// Generated by the build pipeline (minify → convert → this file).
// Stored in flash — tcp_write() references these directly without copying.

typedef struct {
    const char *data;
    uint32_t    length;
} http_response_t;

typedef const http_response_t *(*http_handler_fn)(const char *req, uint16_t len);

// ── Route table entry ─────────────────────────────────────────────────────────
typedef struct {
    const char            *method;    /* "GET" or "POST"   */
    const char            *url;
    const http_response_t *response;  /* non-NULL: static  */
    http_handler_fn        handler;   /* non-NULL: dynamic */
} http_route_t;

// 
static const char s_404[] = "HTTP/1.0 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n";
static const char s_204[] = "HTTP/1.0 204 No Content\r\nContent-Length: 0\r\nConnection: close\r\n\r\n";
static const http_response_t http_404 = { s_404, sizeof(s_404)-1 };
static const http_response_t http_204 = { s_204, sizeof(s_204)-1 };

static const char index_html_data[] =
    "HTTP/1.0 200 OK\r\n"
    "Content-Type: text/html\r\n"
    "Connection: close\r\n"
    "\r\n"
    "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>STM32</title>"
    "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>"
    "<style>"
    "body{font-family:monospace;background:#111;color:#ccc;margin:0;padding:0}"
    ".tabs{display:flex;background:#222}"
    ".tab{padding:8px 18px;background:#333;color:#999;border:none;cursor:pointer;font-size:14px}"
    ".tab.on{background:#111;color:#0f0}"
    ".page{display:none;padding:10px}"
    ".page.on{display:block}"
    "table{border-collapse:collapse;width:100%}"
    "td{border:1px solid #444;padding:5px 8px}"
    "#out{background:#000;color:#0f0;height:380px;padding:8px;"
         "overflow-y:auto;white-space:pre-wrap;word-break:break-all;"
         "font-size:13px;border:1px solid #333}"
    "#irow{display:flex;margin-top:6px;gap:4px}"
    "#inp{flex:1;background:#000;color:#0f0;border:1px solid #444;"
         "padding:4px 6px;font-family:monospace;font-size:13px}"
    "#btn{background:#333;color:#0f0;border:1px solid #444;padding:4px 12px;cursor:pointer}"
    "#ac-cv{width:100%;height:360px;display:block;background:#111}"
    "#ac-hud{font-size:12px;color:#666;padding:4px 0 0 2px;display:flex;align-items:center;gap:10px}"
    "#ac-zero{background:#222;color:#666;border:1px solid #444;padding:2px 8px;"
             "cursor:pointer;font-family:monospace;font-size:12px}"
    "#ac-zero:hover{color:#ccc}"
    "#ac.on{display:flex;gap:8px;align-items:flex-start}"
    "#ac-left{flex:1;min-width:0}"
    "#ac-right{flex:1;min-width:0}"
    "#gr-cv{width:100%;height:360px;display:block;background:#111;border:1px solid #333}"
    "#gr-hud{font-size:12px;color:#666;padding:4px 0 0 2px}"
    "</style></head><body>"
    "<div class=\"tabs\">"
    "<button class=\"tab on\" onclick=\"sw('st',this)\">Active Robot</button>"
    "<button class=\"tab\" onclick=\"sw('tm',this)\">Terminal</button>"
    "<button class=\"tab\" onclick=\"sw('ac',this)\">Board</button>"
    "</div>"

    /* ── Status tab ── */
    "<div id=\"st\" class=\"page on\">"
    "<table><tbody>"
    "<tr><td>Uptime (s)</td><td id=\"sv-uptime_s\">-</td></tr>"
    "<tr><td>UTC Time</td><td id=\"sv-utc_time\">-</td></tr>"
    "<tr><td>Ethernet</td><td id=\"sv-ethernet\">-</td></tr>"
    "<tr><td>USB</td><td id=\"sv-usb\">-</td></tr>"
    "</tbody></table>"
    "</div>"

    /* ── Terminal tab ── */
    "<div id=\"tm\" class=\"page\">"
    "<div id=\"out\"></div>"
    "<div id=\"irow\">"
    "<input id=\"inp\" type=\"text\" autocomplete=\"off\" autocorrect=\"off\""
    " autocapitalize=\"none\" spellcheck=\"false\" placeholder=\"command...\">"
    "<button id=\"btn\" onclick=\"send()\">Send</button>"
    "</div></div>"

    /* ── Board / accelerometer tab ── */
    "<div id=\"ac\" class=\"page\">"
    "<div id=\"ac-left\">"
    "<canvas id=\"ac-cv\"></canvas>"
    "<div id=\"ac-hud\">"
    "<span>"
    "x:&thinsp;<span id=\"ac-x\">-</span>&ensp;"
    "y:&thinsp;<span id=\"ac-y\">-</span>&ensp;"
    "z:&thinsp;<span id=\"ac-z\">-</span>"
    "</span>"
    "<span id=\"ac-taps\">taps:&thinsp;0</span>"
    "<button id=\"ac-zero\" onclick=\"acZero()\">zero</button>"
    "</div>"
    "</div>"
    "<div id=\"ac-right\">"
    "<canvas id=\"gr-cv\"></canvas>"
    "<div style=\"display:flex;align-items:center;gap:8px;margin-top:4px\">"
    "<button id=\"gr-btn\" onclick=\"grToggle()\""
    " style=\"background:#222;color:#0f0;border:1px solid #444;"
             "padding:2px 10px;cursor:pointer;font-family:monospace;"
             "font-size:13px\">&#9654;</button>"
    "<select id=\"gr-src\" onchange=\"grSrcChange()\""
    " style=\"background:#222;color:#aaa;border:1px solid #444;"
             "padding:2px 6px;font-family:monospace;font-size:13px;"
             "cursor:pointer\">"
    "<option value=\"accel\">Accel</option>"
    "<option value=\"mw\">Muscle Wire</option>"
    "</select>"
    "<button id=\"gr-mode\" onclick=\"grModeToggle()\""
    " style=\"background:#222;color:#aaa;border:1px solid #444;"
             "padding:2px 10px;cursor:pointer;font-family:monospace;"
             "font-size:13px\">Raw</button>"
    "<div id=\"gr-hud\" style=\"font-size:12px;color:#666\">no data</div>"
    "</div>"
    "</div>"
    "</div>"

    "<script>"

    /* ── Tab switcher — drives all SSE connect/disconnect ── */
    "function sw(id,el){"
    "document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));"
    "document.querySelectorAll('.tab').forEach(t=>t.classList.remove('on'));"
    "document.getElementById(id).classList.add('on');el.classList.add('on');"
    "if(id==='st')stConnect();else stDisconnect();"
    "if(id==='ac'){acConnect();grConnect();"
    "var gb=document.getElementById('gr-btn');"
    "if(gb)gb.innerHTML=GR.paused?'&#9654;':'&#9646;&#9646;';"
    "}else{acDisconnect();grDisconnect();}}"

    /* ── Status SSE ── */
    "var stEs=null,stEpoch=0,stEpochAt=0,stBase=0,stTick=null;"
    "function fmtUTC(ep){"
    "if(!ep)return'not synced';"
    "var d=new Date(ep*1000),p=n=>String(n).padStart(2,'0');"
    "return d.getUTCFullYear()+'-'+p(d.getUTCMonth()+1)+'-'+p(d.getUTCDate())"
    "+'  '+p(d.getUTCHours())+':'+p(d.getUTCMinutes())+':'+p(d.getUTCSeconds())+' UTC';}"
    "function stTick_fn(){"
    "if(!stEpoch)return;"
    "var el=Math.floor((Date.now()-stEpochAt)/1000);"
    "var eu=document.getElementById('sv-uptime_s');"
    "var et=document.getElementById('sv-utc_time');"
    "if(eu)eu.textContent=stBase+el;"
    "if(et)et.textContent=fmtUTC(stEpoch+el);}"
    "function stConnect(){"
    "if(stEs)return;"
    "stEs=new EventSource('/status_stream');"
    "stEs.onmessage=e=>{"
    "try{"
    "var d=JSON.parse(e.data);"
    "['uptime_s','utc_time','ethernet','usb'].forEach(k=>{"
    "var el=document.getElementById('sv-'+k);"
    "if(el&&d[k]!==undefined)el.textContent=d[k];});"
    "if(d.utc_epoch){stEpoch=d.utc_epoch;stEpochAt=Date.now();stBase=d.uptime_s||0;}"
    "}catch(ex){}};"
    "stEs.onerror=()=>{};"
    "if(!stTick)stTick=setInterval(stTick_fn,1000);}"
    "function stDisconnect(){"
    "if(stEs){stEs.close();stEs=null;}"
    "if(stTick){clearInterval(stTick);stTick=null;}}"

    /* ── Board 3-D visualiser ── */
    /* AC — accelerometer/board namespace */
    "var AC={es:null,ren:null,sc:null,cam:null,brd:null,topMat:null,lastData:0,zeroInv:null,"
           "tapLed:null,tapAt:0,tapCount:0};"

    "function acInit(){"
    "if(!window.THREE)return;"                              /* CDN not loaded */
    "var cv=document.getElementById('ac-cv');"
    "cv.width=cv.offsetWidth||640;cv.height=360;"
    "AC.ren=new THREE.WebGLRenderer({canvas:cv,antialias:true});"
    "AC.ren.setSize(cv.width,cv.height);"
    "AC.ren.setClearColor(0x111111);"
    "AC.sc=new THREE.Scene();"
    "AC.cam=new THREE.PerspectiveCamera(45,cv.width/360,0.1,100);"
    "AC.cam.position.set(0,2.6,4.2);"
    "AC.cam.lookAt(0,0,0);"
    /* Lighting */
    "AC.sc.add(new THREE.AmbientLight(0xffffff,0.45));"
    "var dl=new THREE.DirectionalLight(0xffffff,0.85);"
    "dl.position.set(1.5,3,2.5);AC.sc.add(dl);"
    /* PCB board: 2×0.08×1.4 box, per-face materials */
    /* Face order: +x,-x,+y(top),-y(bottom),+z,-z */
    "var side=new THREE.MeshLambertMaterial({color:0x1a5e1a});"
    "AC.topMat=new THREE.MeshLambertMaterial({color:0x2a8c2a});"
    "var bot=new THREE.MeshLambertMaterial({color:0x0d3d0d});"
    "AC.brd=new THREE.Mesh("
    "new THREE.BoxGeometry(2.0,0.08,1.4),"
    "[side,side,AC.topMat,bot,side,side]);"
    "AC.sc.add(AC.brd);"
    /* Four LEDs — LD3 orange, LD4 green, LD5 red, LD6 blue */
    /* Positioned near right edge of the board top face.   */
    /* LD3 material is kept in AC.tapLed for the tap flash. */
    "AC.tapLed=new THREE.MeshBasicMaterial({color:0xff6600});"
    "var ld3=new THREE.Mesh(new THREE.BoxGeometry(0.09,0.09,0.09),AC.tapLed);"
    "ld3.position.set(0.78,0.085,0.44);AC.brd.add(ld3);"
    "[{c:0x00ff00,z:0.22},{c:0xff2200,z:0},{c:0x2255ff,z:-0.22}]"
    ".forEach(function(l){"
    "var m=new THREE.Mesh("
    "new THREE.BoxGeometry(0.09,0.09,0.09),"
    "new THREE.MeshBasicMaterial({color:l.c}));"
    "m.position.set(0.78,0.085,l.z);"
    "AC.brd.add(m);});"
    /* MCU footprint — dark square on top face */
    "var mcu=new THREE.Mesh("
    "new THREE.BoxGeometry(0.55,0.05,0.55),"
    "new THREE.MeshLambertMaterial({color:0x1c1c1c}));"
    "mcu.position.set(-0.2,0.065,0);"
    "AC.brd.add(mcu);"
    /* Render loop — board color shows data-flow state:                  */
    /*   green  = samples arriving  (sampling on)                        */
    /*   grey   = no data >2 s      (sampling stopped / disconnected)    */
    /* LD3 flashes white on tap then fades back to orange over 400 ms.   */
    "(function loop(){"
    "requestAnimationFrame(loop);"
    "var live=AC.lastData&&(Date.now()-AC.lastData<3000);"
    "AC.topMat.color.setHex(live?0x2a8c2a:0x3a3a3a);"
    "if(AC.tapAt){"
    "var t=Math.min(1,(Date.now()-AC.tapAt)/400);"
    "AC.tapLed.color.setRGB(1,1-0.6*t,1-t);"   /* white → orange */
    "if(t>=1){AC.tapLed.color.setHex(0xff6600);AC.tapAt=0;}}"
    "AC.ren.render(AC.sc,AC.cam);"
    "})();}"

    "function acConnect(){"
    "if(AC.es)return;"
    "if(!AC.ren)acInit();"
    "AC.es=new EventSource('/accel_stream');"
    "AC.es.onmessage=function(e){"
    "try{"
    "var d=JSON.parse(e.data);"
    /* {"run":0} — accel stopped; go grey immediately, skip orientation. */
    "if(d.run===0){AC.lastData=0;return;}"
    /* {"run":1} — accel started; prime lastData so colour turns green   */
    /*             before the first orientation packet arrives.          */
    "if(d.run===1){AC.lastData=Date.now();return;}"
    /* x/y/z are normalised gravity components × 1000 from firmware.   */
    /* Y is up when the board is flat; quaternion handles any tilt.     */
    "var gx=d.x/1000,gy=d.y/1000,gz=d.z/1000;"
    "var gv=new THREE.Vector3(gx,gy,gz).normalize();"
    "var q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),gv);"
    "if(AC.zeroInv)q.multiply(AC.zeroInv);"
    "if(AC.brd)AC.brd.quaternion.copy(q);"
    "document.getElementById('ac-x').textContent=gx.toFixed(3);"
    "document.getElementById('ac-y').textContent=gy.toFixed(3);"
    "document.getElementById('ac-z').textContent=gz.toFixed(3);"
    "if(d.t){AC.tapAt=Date.now();AC.tapCount++;"
    "var te=document.getElementById('ac-taps');"
    "if(te)te.textContent='taps:\u2009'+AC.tapCount;}"
    "AC.lastData=Date.now();"
    "}catch(ex){}};"
    "AC.es.onerror=function(){};}"

    /* acZero — capture inverse of current board quaternion as the reference.  */
    /* Subsequent orientations are displayed relative to this baseline, so    */
    /* whatever tilt exists when Zero is pressed maps to the model flat.      */
    "function acZero(){"
    "if(!AC.brd)return;"
    "AC.zeroInv=new THREE.Quaternion().copy(AC.brd.quaternion).conjugate();"
    "AC.brd.quaternion.set(0,0,0,1);}"   /* snap to flat immediately */

    "function acDisconnect(){"
    "if(AC.es){AC.es.close();AC.es=null;}}"

    /* ── Graph — sweep display + capture viewer ──────────────────────────── */
    /* Live mode: firmware sends {"live":[x0,y0,z0,…x9,y9,z9]} at 100 ms   */
    /*   intervals.  Browser writes into a 1000-sample ring buffer and      */
    /*   redraws a sweep oscilloscope trace (ring position = canvas x).     */
    /* Capture mode: {"ch","s","d"} chunks + {"done":1} — static snapshot.  */
    /* ▶/⏸ button connects / disconnects the SSE stream.                    */
    /* X = green  Y = blue  Z = red  (g-units, ±2.0 g range)                */
    "var GR_WIN=1000;"
    "var GR={"
    "es:null,"
    "paused:false,"       /* user pressed pause */
    "rawMode:true,"       /* true=raw unfiltered, false=IIR refined */
    "ring:{x:new Float32Array(GR_WIN),y:new Float32Array(GR_WIN),"
           "z:new Float32Array(GR_WIN),wi:0,n:0},"
    "bufs:{x:null,y:null,z:null}"  /* capture snapshot */
    "};"
    /* grInit — size canvas to its rendered width */
    "function grInit(){"
    "var cv=document.getElementById('gr-cv');"
    "if(!cv)return;"
    "cv.width=cv.offsetWidth||480;cv.height=360;}"
    /* ── Sweep draw (live) ── */
    "function grDrawSweep(){"
    "var cv=document.getElementById('gr-cv');"
    "if(!cv||!cv.width)grInit();"
    "var ctx=cv.getContext('2d'),W=cv.width,H=cv.height;"
    "var r=GR.ring,n=Math.min(r.n,GR_WIN);"
    "ctx.fillStyle='#111';ctx.fillRect(0,0,W,H);"
    "if(!n)return;"
    /* auto-scale across all three channels */
    "var mn=Infinity,mx=-Infinity,chrs=[r.x,r.y,r.z];"
    "for(var c=0;c<3;c++){for(var i=0;i<GR_WIN;i++){"
    "if(chrs[c][i]<mn)mn=chrs[c][i];if(chrs[c][i]>mx)mx=chrs[c][i];}}"
    "if(mn===mx){mn-=1;mx+=1;}"
    "var ml=46,mr=8,mt=10,mb=22,pw=W-ml-mr,ph=H-mt-mb;"
    /* y-grid */
    "ctx.font='10px monospace';ctx.textAlign='right';"
    "for(var s=0;s<=5;s++){"
    "var gy=mt+ph*s/5;"
    "ctx.strokeStyle='#1e1e1e';ctx.lineWidth=1;"
    "ctx.beginPath();ctx.moveTo(ml,gy);ctx.lineTo(ml+pw,gy);ctx.stroke();"
    "ctx.fillStyle='#555';ctx.fillText((mx-(mx-mn)*s/5).toFixed(3),ml-3,gy+3);}"
    /* axes */
    "ctx.strokeStyle='#444';ctx.lineWidth=1;"
    "ctx.beginPath();ctx.moveTo(ml,mt);ctx.lineTo(ml,mt+ph);"
    "ctx.lineTo(ml+pw,mt+ph);ctx.stroke();"
    /* cursor gap — dark bar at the write-head position */
    "var cur=r.wi%GR_WIN,cx=ml+pw*cur/GR_WIN;"
    "ctx.fillStyle='#333';ctx.fillRect(cx,mt,3,ph);"
    /* three channel lines — ring position maps directly to canvas x */
    "var cols=['#0f0','#08f','#f55'];"
    "for(var c=0;c<3;c++){"
    "var ch=chrs[c];"
    "ctx.strokeStyle=cols[c];ctx.lineWidth=1.5;ctx.beginPath();"
    "for(var i=0;i<GR_WIN;i++){"
    "var px=ml+pw*i/GR_WIN,py=mt+ph*(1-(ch[i]-mn)/(mx-mn));"
    "if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}"
    "ctx.stroke();}"
    /* hud */
    "var h=document.getElementById('gr-hud');"
    "var src=document.getElementById('gr-src');"
    "var leg=(src&&src.value==='mw')"
    "?'Vsup(V)=green  Rwire(\u03a9)=blue  PWM%=red'"
    ":'x=green  y=blue  z=red  g';"
    "if(h)h.textContent='live  n='+n+'  min='+mn.toFixed(3)+'  max='+mx.toFixed(3)"
    "+'  \u2014  '+leg;}"
    /* ── Capture draw (static snapshot) ── */
    "function grDraw(){"
    "var cv=document.getElementById('gr-cv');"
    "if(!cv||!cv.width)grInit();"
    "var ctx=cv.getContext('2d'),W=cv.width,H=cv.height;"
    "ctx.fillStyle='#111';ctx.fillRect(0,0,W,H);"
    "var chs=[{k:'x',c:'#0f0'},{k:'y',c:'#08f'},{k:'z',c:'#f55'}];"
    "var valid=chs.filter(function(c){return GR.bufs[c.k]&&GR.bufs[c.k].length;});"
    "if(!valid.length){"
    "ctx.fillStyle='#444';ctx.font='13px monospace';ctx.textAlign='center';"
    "ctx.fillText('no data',W/2,H/2);return;}"
    "var mn=Infinity,mx=-Infinity;"
    "valid.forEach(function(ch){var d=GR.bufs[ch.k];"
    "for(var i=0;i<d.length;i++){if(d[i]<mn)mn=d[i];if(d[i]>mx)mx=d[i];}});"
    "if(mn===mx){mn-=1;mx+=1;}"
    "var n=GR.bufs[valid[0].k].length;"
    "var ml=46,mr=8,mt=10,mb=22,pw=W-ml-mr,ph=H-mt-mb;"
    "ctx.font='10px monospace';ctx.textAlign='right';"
    "for(var s=0;s<=5;s++){"
    "var gy=mt+ph*s/5;"
    "ctx.strokeStyle='#1e1e1e';ctx.lineWidth=1;"
    "ctx.beginPath();ctx.moveTo(ml,gy);ctx.lineTo(ml+pw,gy);ctx.stroke();"
    "ctx.fillStyle='#555';ctx.fillText((mx-(mx-mn)*s/5).toFixed(3),ml-3,gy+3);}"
    "ctx.strokeStyle='#444';ctx.lineWidth=1;"
    "ctx.beginPath();ctx.moveTo(ml,mt);ctx.lineTo(ml,mt+ph);"
    "ctx.lineTo(ml+pw,mt+ph);ctx.stroke();"
    "valid.forEach(function(ch){"
    "var d=GR.bufs[ch.k],cnt=d.length;"
    "ctx.strokeStyle=ch.c;ctx.lineWidth=1.5;ctx.beginPath();"
    "for(var i=0;i<cnt;i++){"
    "var px=ml+pw*i/(cnt>1?cnt-1:1),py=mt+ph*(1-(d[i]-mn)/(mx-mn));"
    "if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.stroke();});"
    "var h=document.getElementById('gr-hud');"
    "if(h)h.textContent='capture  n='+n+'  min='+mn.toFixed(3)+'  max='+mx.toFixed(3)"
    "+'  g  \u2014  x=green  y=blue  z=red';}"
    /* ── SSE connection management ── */
    /* grSrcChange — called when the source dropdown changes.               */
    /* Clears the ring buffer, disconnects the current stream, hides the   */
    /* Raw button when Muscle Wire is selected, then reconnects.           */
    "function grSrcChange(){"
    "grDisconnect();"
    "GR.ring.x.fill(0);GR.ring.y.fill(0);GR.ring.z.fill(0);"
    "GR.ring.wi=0;GR.ring.n=0;"
    "var h=document.getElementById('gr-hud');"
    "if(h)h.textContent='no data';"
    "var mb=document.getElementById('gr-mode');"
    "var src=document.getElementById('gr-src');"
    "if(mb)mb.style.display=(src&&src.value==='mw')?'none':'';"
    "if(!GR.paused)grConnect();}"
    "function grConnect(){"
    "if(GR.es||GR.paused)return;"
    "if(!document.getElementById('gr-cv').width)grInit();"
    "var src=document.getElementById('gr-src');"
    "var url=(src&&src.value==='mw')?'/mw_stream':'/graph_stream';"
    "GR.es=new EventSource(url);"
    "GR.es.onmessage=function(e){"
    "try{"
    "var p=JSON.parse(e.data);"
    /* live burst: interleaved x,y,z triples */
    "if(p.live){"
    "var arr=p.live,r=GR.ring;"
    "for(var i=0;i<arr.length;i+=3){"
    "var wi=r.wi%GR_WIN;"
    "r.x[wi]=arr[i];r.y[wi]=arr[i+1];r.z[wi]=arr[i+2];"
    "r.wi++;if(r.n<GR_WIN)r.n++;}"
    "grDrawSweep();"
    /* capture chunk: accumulate by channel */
    "}else if(p.ch&&p.d){"
    "if(!GR.bufs[p.ch])GR.bufs[p.ch]=[];"
    "var s=p.s||0;"
    "for(var i=0;i<p.d.length;i++)GR.bufs[p.ch][s+i]=p.d[i];"
    /* capture done: draw static snapshot */
    "}else if(p.done){grDraw();}"
    "}catch(ex){}};"
    "GR.es.onerror=function(){};}"
    "function grDisconnect(){"
    "if(GR.es){GR.es.close();GR.es=null;}}"
    /* ▶/⏸ toggle — connects or disconnects the SSE stream */
    "function grToggle(){"
    "GR.paused=!GR.paused;"
    "var btn=document.getElementById('gr-btn');"
    "if(GR.paused){grDisconnect();if(btn)btn.innerHTML='&#9654;';}"
    "else{grConnect();if(btn)btn.innerHTML='&#9646;&#9646;';}}"
    /* Raw/Refined toggle — sends mode to firmware and updates button label */
    "function grModeToggle(){"
    "GR.rawMode=!GR.rawMode;"
    "var mb=document.getElementById('gr-mode');"
    "if(mb){mb.textContent=GR.rawMode?'Raw':'Refined';"
    "mb.style.color=GR.rawMode?'#aaa':'#4af';}"
    "fetch('/graph_mode',{method:'POST',"
    "body:GR.rawMode?'raw':'ref',headers:{'Content-Type':'text/plain'}});"
    /* clear ring so stale data from the previous mode doesn't linger */
    "GR.ring.x.fill(0);GR.ring.y.fill(0);GR.ring.z.fill(0);"
    "GR.ring.wi=0;GR.ring.n=0;}"

    /* ── Visibility / focus management ── */
    "document.addEventListener('visibilitychange',()=>{"
    "if(document.hidden){stDisconnect();acDisconnect();grDisconnect();}"
    "else{"
    "if(document.getElementById('st').classList.contains('on'))stConnect();"
    "if(document.getElementById('ac').classList.contains('on')){acConnect();grConnect();}}});"

    /* Auto-connect on load — status tab is default */
    "stConnect();"

    /* ── Terminal SSE ── */
    "(function(){"
    "const o=document.getElementById('out');"
    "const es=new EventSource('/term_stream');"
    "es.onmessage=function(e){o.textContent+=e.data;o.scrollTop=o.scrollHeight;};"
    "es.onerror=function(){};"
    "})();"

    /* ── Terminal input ── */
    "var hist=[],histIdx=0;"
    "function send(){"
    "const el=document.getElementById('inp');"
    "const txt=el.value;el.value='';"
    "if(txt){hist.push(txt);histIdx=hist.length;}"
    "const enc=new TextEncoder().encode(txt);"
    "const buf=new Uint8Array(enc.length+1);"
    "buf.set(enc);buf[enc.length]=0xD;"
    "fetch('/term_in',{method:'POST',body:buf}).catch(()=>{});}"
    "document.getElementById('inp')"
    ".addEventListener('keydown',e=>{"
    "if(e.key==='Enter'){send();}"
    "else if(e.key==='ArrowUp'){e.preventDefault();"
    "if(histIdx>0){histIdx--;e.target.value=hist[histIdx];}}"
    "else if(e.key==='ArrowDown'){e.preventDefault();"
    "if(histIdx<hist.length-1){histIdx++;e.target.value=hist[histIdx];}"
    "else{histIdx=hist.length;e.target.value='';}}});"
    "</script></body></html>";

static const http_response_t resp_index = {
    index_html_data,
    sizeof(index_html_data) - 1   /* exclude null terminator */
};

#endif // HTTP_CONTENT_H
