#ifndef HTTP_CONTENT_H
#define HTTP_CONTENT_H

#include <stdint.h>
#include "byteq.h"
#include "cli.h"

// ── Flash-resident HTTP response ──────────────────────────────────────────────
// Each entry is a complete HTTP response: status line + headers + blank + body.
// Generated by the build pipeline (minify → convert → this file).
// Stored in flash — tcp_write() references these directly without copying.

typedef struct {
    const char *data;
    uint32_t    length;
} http_response_t;

typedef const http_response_t *(*http_handler_fn)(const char *req, uint16_t len);

// ── Route table entry ─────────────────────────────────────────────────────────
typedef struct {
    const char            *method;    /* "GET" or "POST"   */
    const char            *url;
    const http_response_t *response;  /* non-NULL: static  */
    http_handler_fn        handler;   /* non-NULL: dynamic */
} http_route_t;

// 
static const char s_404[] = "HTTP/1.0 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n";
static const char s_204[] = "HTTP/1.0 204 No Content\r\nContent-Length: 0\r\nConnection: close\r\n\r\n";
static const http_response_t http_404 = { s_404, sizeof(s_404)-1 };
static const http_response_t http_204 = { s_204, sizeof(s_204)-1 };

static const char index_html_data[] =
    "HTTP/1.0 200 OK\r\n"
    "Content-Type: text/html\r\n"
    "Connection: close\r\n"
    "\r\n"
    "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>STM32</title>"
    "<style>"
    "body{font-family:monospace;background:#111;color:#ccc;margin:0;padding:0}"
    ".tabs{display:flex;background:#222}"
    ".tab{padding:8px 18px;background:#333;color:#999;border:none;cursor:pointer;font-size:14px}"
    ".tab.on{background:#111;color:#0f0}"
    ".page{display:none;padding:10px}"
    ".page.on{display:block}"
    "table{border-collapse:collapse;width:100%}"
    "td{border:1px solid #444;padding:5px 8px}"
    "#out{background:#000;color:#0f0;height:380px;padding:8px;"
         "overflow-y:auto;white-space:pre-wrap;word-break:break-all;"
         "font-size:13px;border:1px solid #333}"
    "#irow{display:flex;margin-top:6px;gap:4px}"
    "#inp{flex:1;background:#000;color:#0f0;border:1px solid #444;"
         "padding:4px 6px;font-family:monospace;font-size:13px}"
    "#btn{background:#333;color:#0f0;border:1px solid #444;padding:4px 12px;cursor:pointer}"
    "</style></head><body>"
    "<div class=\"tabs\">"
    "<button class=\"tab on\" onclick=\"sw('st',this)\">Active Robot</button>"
    "<button class=\"tab\" onclick=\"sw('tm',this)\">Terminal</button>"
    "</div>"
    "<div id=\"st\" class=\"page on\">"
    "<table><tbody>"
    "<tr><td>Uptime (s)</td><td id=\"sv-uptime_s\">-</td></tr>"
    "<tr><td>UTC Time</td><td id=\"sv-utc_time\">-</td></tr>"
    "<tr><td>Ethernet</td><td id=\"sv-ethernet\">-</td></tr>"
    "<tr><td>USB</td><td id=\"sv-usb\">-</td></tr>"
    "</tbody></table>"
    "</div>"
    "<div id=\"tm\" class=\"page\">"
    "<div id=\"out\"></div>"
    "<div id=\"irow\">"
    "<input id=\"inp\" type=\"text\" autocomplete=\"off\" autocorrect=\"off\""
    " autocapitalize=\"none\" spellcheck=\"false\" placeholder=\"command...\">"
    "<button id=\"btn\" onclick=\"send()\">Send</button>"
    "</div></div>"
    "<script>"
    "function sw(id,el){"
    "document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));"
    "document.querySelectorAll('.tab').forEach(t=>t.classList.remove('on'));"
    "document.getElementById(id).classList.add('on');el.classList.add('on');"
    "if(id==='st')stConnect();else stDisconnect();}"

    /* status SSE — push driven, connect only while status tab is active */
    "var stEs=null,stEpoch=0,stEpochAt=0,stBase=0,stTick=null;"

    /* local UTC formatter — no network round-trip */
    "function fmtUTC(ep){"
    "if(!ep)return'not synced';"
    "var d=new Date(ep*1000),p=n=>String(n).padStart(2,'0');"
    "return d.getUTCFullYear()+'-'+p(d.getUTCMonth()+1)+'-'+p(d.getUTCDate())"
    "+'  '+p(d.getUTCHours())+':'+p(d.getUTCMinutes())+':'+p(d.getUTCSeconds())+' UTC';}"

    /* 1-second tick: update uptime + UTC between SSE pushes — no network */
    "function stTick_fn(){"
    "if(!stEpoch)return;"
    "var el=Math.floor((Date.now()-stEpochAt)/1000);"
    "var eu=document.getElementById('sv-uptime_s');"
    "var et=document.getElementById('sv-utc_time');"
    "if(eu)eu.textContent=stBase+el;"
    "if(et)et.textContent=fmtUTC(stEpoch+el);}"

    "function stConnect(){"
    "if(stEs)return;"
    "stEs=new EventSource('/status_stream');"
    "stEs.onmessage=e=>{"
    "try{"
    "var d=JSON.parse(e.data);"
    "['uptime_s','utc_time','ethernet','usb'].forEach(k=>{"
    "var el=document.getElementById('sv-'+k);"
    "if(el&&d[k]!==undefined)el.textContent=d[k];});"
    "if(d.utc_epoch){stEpoch=d.utc_epoch;stEpochAt=Date.now();stBase=d.uptime_s||0;}"
    "}catch(ex){}};"
    "stEs.onerror=()=>{};"
    "if(!stTick)stTick=setInterval(stTick_fn,1000);}"

    "function stDisconnect(){"
    "if(stEs){stEs.close();stEs=null;}"
    "if(stTick){clearInterval(stTick);stTick=null;}}"

    /* pause SSE when browser tab is hidden; resume when visible again */
    "document.addEventListener('visibilitychange',()=>{"
    "if(document.hidden)stDisconnect();"
    "else if(document.getElementById('st').classList.contains('on'))stConnect();});"

    /* auto-connect on load — status tab is the default active tab */
    "stConnect();"

    /* terminal SSE stream — push output from /term_stream */
    "(function(){"
    "const o=document.getElementById('out');"
    "const es=new EventSource('/term_stream');"
    "es.onmessage=function(e){o.textContent+=e.data;o.scrollTop=o.scrollHeight;};"
    "es.onerror=function(){};"
    "})();"

    /* command history (up/down arrows) + send (Enter or button) */
    "var hist=[],histIdx=0;"
    "function send(){"
    "const el=document.getElementById('inp');"
    "const txt=el.value;el.value='';"
    "if(txt){hist.push(txt);histIdx=hist.length;}"
    "const enc=new TextEncoder().encode(txt);"
    "const buf=new Uint8Array(enc.length+1);"
    "buf.set(enc);buf[enc.length]=0xD;"
    "fetch('/term_in',{method:'POST',body:buf}).catch(()=>{});}"

    "document.getElementById('inp')"
    ".addEventListener('keydown',e=>{"
    "if(e.key==='Enter'){send();}"
    "else if(e.key==='ArrowUp'){e.preventDefault();"
    "if(histIdx>0){histIdx--;e.target.value=hist[histIdx];}}"
    "else if(e.key==='ArrowDown'){e.preventDefault();"
    "if(histIdx<hist.length-1){histIdx++;e.target.value=hist[histIdx];}"
    "else{histIdx=hist.length;e.target.value='';}}});"
    "</script></body></html>";

static const http_response_t resp_index = {
    index_html_data,
    sizeof(index_html_data) - 1   /* exclude null terminator */
};

#endif // HTTP_CONTENT_H
