#!/usr/bin/env python3
"""
build_fsdata.py  -  Generate lwIP fsdata.c from a directory of web files.

Usage:
  python build_fsdata.py [fs_dir] [output.c] [--no-gzip]

Defaults:
  fs_dir   = fs/
  output   = fsdata.c
  gzip     = enabled (for .html .css .js .json .svg .txt)
"""

import os, sys, gzip, io

CONTENT_TYPES = {
    '.html': 'text/html',
    '.htm':  'text/html',
    '.css':  'text/css',
    '.js':   'application/javascript',
    '.json': 'application/json',
    '.png':  'image/png',
    '.jpg':  'image/jpeg',
    '.ico':  'image/x-icon',
    '.svg':  'image/svg+xml',
    '.txt':  'text/plain',
}

COMPRESSIBLE = {'.html', '.htm', '.css', '.js', '.json', '.svg', '.txt'}

def make_http_header(filename, gzipped):
    ext = os.path.splitext(filename)[1].lower()
    ct = CONTENT_TYPES.get(ext, 'application/octet-stream')
    parts = ['HTTP/1.0 200 OK', 'Content-Type: ' + ct]
    if gzipped:
        parts.append('Content-Encoding: gzip')
    parts += ['', '']                          # blank line = end of headers
    return '\r\n'.join(parts).encode('ascii')

def gzip_compress(data):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode='wb', mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()

def safe_var(url_path):
    """'/index.html' -> '_index_html'"""
    return url_path.replace('/', '_').replace('.', '_').replace('-', '_')

def bytes_to_c(data, indent='    '):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append(indent + ', '.join('0x{:02x}'.format(b) for b in chunk) + ',')
    return '\n'.join(lines)

def generate(fs_dir, out_path, do_gzip=True):
    entries = []

    for root, dirs, names in os.walk(fs_dir):
        dirs.sort()
        for name in sorted(names):
            fp   = os.path.join(root, name)
            url  = '/' + os.path.relpath(fp, fs_dir).replace('\\', '/')
            raw  = open(fp, 'rb').read()
            ext  = os.path.splitext(name)[1].lower()

            gz   = do_gzip and (ext in COMPRESSIBLE)
            body = gzip_compress(raw) if gz else raw
            hdr  = make_http_header(name, gz)

            # data array layout:  [url\0][HTTP header][body]
            fname_bytes = url.encode('ascii') + b'\x00'
            full        = fname_bytes + hdr + body

            entries.append({
                'url':      url,
                'full':     full,
                'fname_len': len(fname_bytes),
                'vardata':  'data' + safe_var(url),
                'varfile':  'file' + safe_var(url),
                'gz':       gz,
                'raw_len':  len(raw),
                'out_len':  len(body),
            })

    out = []
    out.append('/* Auto-generated by build_fsdata.py — do not edit */')
    out.append('#include "lwip/apps/fs.h"')
    out.append('')

    for e in entries:
        out.append('static const unsigned char ' + e['vardata'] + '[] = {')
        out.append('    /* ' + e['url'] + ' */')
        out.append(bytes_to_c(e['full']))
        out.append('};')
        out.append('')

    prev = 'NULL'
    for e in entries:
        vd = e['vardata']
        vf = e['varfile']
        fl = e['fname_len']
        out.append('static const struct fsdata_file ' + vf + '[] = { {')
        out.append('    ' + prev + ',')
        out.append('    ' + vd + ',')
        out.append('    ' + vd + ' + ' + str(fl) + ',')
        out.append('    sizeof(' + vd + ') - ' + str(fl) + ',')
        out.append('    FS_FILE_FLAGS_HEADER_INCLUDED')
        out.append('} };')
        out.append('')
        prev = '&' + vf + '[0]'

    out.append('const struct fsdata_file * const fs_root = ' + prev + ';')
    out.append('const int fs_numfiles = ' + str(len(entries)) + ';')
    out.append('')
    out.append('#define FS_ROOT fs_root')
    out.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(out))

    print('Generated {} ({} file{})'.format(out_path, len(entries),
                                             's' if len(entries) != 1 else ''))
    for e in entries:
        ratio = ' [{}->{} bytes, gzip]'.format(e['raw_len'], e['out_len']) if e['gz'] \
                else ' [{} bytes]'.format(e['out_len'])
        print('  {:35s}{}'.format(e['url'], ratio))

if __name__ == '__main__':
    args  = [a for a in sys.argv[1:] if not a.startswith('--')]
    flags = [a for a in sys.argv[1:] if a.startswith('--')]
    fs_dir   = args[0] if len(args) > 0 else 'fs'
    out_path = args[1] if len(args) > 1 else 'fsdata.c'
    do_gzip  = '--no-gzip' not in flags
    generate(fs_dir, out_path, do_gzip)